language: node_js

cache:
  yarn: true
  directories:
    - node_modules
    - examples/simple/node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn
  - yarn --cwd examples/simple/

branches:
  only:
    - master
env:
  - TEST_TYPE=export
  - TEST_TYPE=server
