#!/usr/bin/env bash

set -ev

yarn link
cd examples/simple
yarn
yarn link phox
npx phox
zip -r website.zip out
curl -H "Content-Type: application/zip" \
     -H "Authorization: Bearer $NETLIFY_TOKEN" \
     --data-binary "@website.zip" \
     https://api.netlify.com/api/v1/sites/phox/deploys
