#!/usr/bin/env bash

set -ev

cd examples/simple
yarn upgrade phox --cwd examples/simple/

zip -r website.zip ./out

curl -H "Content-Type: application/zip" \
     -H "Authorization: Bearer $NETLIFY_KEY" \
     --data-binary "@website.zip" \
     https://api.netlify.com/api/v1/sites/phox.netlify.com/deploys
