#!/usr/bin/env bash

set -ev

EXIT_CODE=0

yarn run build
cd examples/simple
yarn
cp ../../index.js node_modules/phox/
cp -fRv ../../lib node_modules/phox/
cp -fRv ../../bin node_modules/phox/
PHOX_BUILD_ID=snapshot  node ./node_modules/phox/bin/phox
npx serve -l 9999 > /dev/null 2>&1 &
PID=$!
sleep 5
cd ../..
if [ "$1" == "-u" ]; then
  npx jest -u export || EXIT_CODE=1
else
  npx jest export || EXIT_CODE=1
fi
kill $PID || { echo "No process associated with pid $PID running."; }
if [[ "$EXIT_CODE" == "1" ]]; then
  exit $EXIT_CODE
fi
