#!/usr/bin/env bash

set -ev

EXIT_CODE=0

yarn run build
cd examples/simple
yarn
yarn add serve
cp ../../server.js node_modules/phox/
cp ../../export.js node_modules/phox/
cp -r ../../lib/ node_modules/phox/lib/
cp -r ../../bin/ node_modules/phox/bin/
node ./node_modules/phox/bin/phox
npx serve -n -p 9999 -S -u ./out > /dev/null 2>&1 &
PID=$!
sleep 5
cd ../..
if [ "$1" == "-u" ]; then
  npx jest -u --testRegex="\/export\/" || EXIT_CODE=1
else
  npx jest --testRegex="\/export\/" || EXIT_CODE=1
fi
kill $PID
cd examples/simple
yarn remove serve
cd ../..
exit $EXIT_CODE
